<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Quiz Analytics Report</title>
    <style>
        @page { margin: 40px 40px; }
        body { font-family: DejaVu Sans, Arial, Helvetica, sans-serif; font-size: 12px; color: #222; }
        header { position: fixed; top: -10px; left: 0; right: 0; height: 60px; }
    .header-inner { display:flex; align-items:center; gap:12px; }
    .logo { height:48px; }
    .title { font-size:18px; font-weight:700; }
        .meta { margin-top:6px; color:#666; font-size:12px; }

        footer { position: fixed; bottom: -20px; left: 0; right: 0; height: 40px; text-align:center; font-size:11px; color:#666; }
        .pagenum:before { content: counter(page); }

        .content { margin-top: 70px; margin-bottom: 60px; }

    .kpi { display:flex; gap:12px; margin-bottom:16px; }
    .kpi .card { background:#f7f7f9; border-radius:6px; padding:10px 12px; flex:1; }
    .kpi .card .value { font-size:18px; font-weight:700; color: #111 }
    .kpi .card .label { color:#666; font-size:11px }
    .kpi .card.accent { border-left:6px solid {{ $brandColor ?? '#7c3aed' }}; }
        table { border-collapse: collapse; width:100%; margin-top:8px; }
        table th, table td { border:1px solid #ddd; padding:8px; text-align:left; vertical-align:top; }
    table thead th { background: {{ $brandColor ?? '#7c3aed' }}; color: #fff; }

        .question-text { max-width:600px; white-space:normal; word-wrap:break-word; }

        .page-break { page-break-after: always; }

    </style>
</head>
<body>
<header>
    <div class="header-inner">
        @if(!empty($logoData))
            @if(!empty($logoIsSvg) && $logoIsSvg)
                {{-- Inline raw SVG for best fidelity --}}
                <div class="logo">{!! $logoData !!}</div>
            @else
                <img class="logo" src="{{ $logoData }}" alt="logo" />
            @endif
        @endif
        <div>
            <div class="title">Quiz Analytics Report</div>
            <div class="meta">Quiz ID: {{ $quiz->id }} &mdash; Generated: {{ \Carbon\Carbon::now()->toDayDateTimeString() }}</div>
        </div>
    </div>
</header>

<footer>
    <div style="display:flex;justify-content:space-between;align-items:center;padding:6px 12px 0 12px;">
        <div>Generated by Modeh • Page <span class="pagenum"></span></div>
        <div style="font-size:11px;color:#666;">https://modeh.app</div>
    </div>
    <div style="height:6px"></div>
</footer>

<main class="content">
    <div class="kpi">
        <div class="card accent"><strong class="label">Attempts</strong><div class="value">{{ $analytics['attempts_count'] }}</div></div>
        <div class="card"><strong class="label">Completions</strong><div class="value">{{ $analytics['completions'] }}</div></div>
        <div class="card"><strong class="label">Avg Score</strong><div class="value">{{ $analytics['avg_score'] }}</div></div>
        <div class="card"><strong class="label">Avg Time (s)</strong><div class="value">{{ $analytics['avg_time_seconds'] }}</div></div>
    </div>

    <h3>Per-question performance</h3>
    <table>
        <thead>
            <tr>
                <th style="width:60px">Q ID</th>
                <th>Question</th>
                <th style="width:90px">Attempts</th>
                <th style="width:90px">Correct</th>
                <th style="width:90px">Correct %</th>
            </tr>
        </thead>
        <tbody>
            @foreach($analytics['per_question'] as $q)
                <tr>
                    <td>{{ $q['question_id'] }}</td>
                    <td class="question-text">{!! e(mb_substr($q['body'] ?? '', 0, 800)) !!}</td>
                    <td>{{ $q['attempts_count'] ?? 0 }}</td>
                    <td>{{ $q['correct_count'] ?? 0 }}</td>
                    <td>{{ isset($q['correct_rate']) ? number_format($q['correct_rate']*100,1) . '%' : '-' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="page-break"></div>

    <h3>Score distribution</h3>
    <table>
        <thead>
            <tr><th>Range</th><th>Count</th></tr>
        </thead>
        <tbody>
            @foreach($analytics['score_distribution'] as $i => $count)
                <tr>
                    <td>{{ $i*10 }} - {{ $i*10 + 9 }}{{ $i == 10 ? ' (100)' : '' }}</td>
                    <td>{{ $count }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

</main>
</body>
</html>